### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by UnderDev** [UnderDev/TheoryOfAlgorithms-Countdown#1]
Things to keep in mind during the project.

- [x] Initial Project Setup. 
- [x] Create Lists Containing Small/Large/Operators.
- [x] Generate Random Target Number.
- [x] ReadMe - "OnGoing"
- [ ] Randomly Pick 6 numbers From Lists of Small/Large Numbers for Chosen Nums
